fn main() { 
    # This should fail but probably compiles incorrectly
    bad1 = 5 + [1, 2]
    out("This should not work")
}
